name = "Cpc"
version = "0.1.0"
defaultTargets = ["Cpc", "CpcMini"]

[[lean_lib]]
name = "Cpc"

[[lean_lib]]
name = "CpcMini"

[[lean_exe]]
name = "logos"
root = "Main"
supportInterpreter = true

[[lean_exe]]
name = "logos2"
root = "Main2"
