name = "Cpc"
version = "0.1.0"
defaultTargets = ["Logos", "Cpc", "CpcMini"]

[[lean_lib]]
name = "Logos"

[[lean_lib]]
name = "Cpc"
moreLeanArgs = ["-DmaxHeartbeats=10000000"]

[[lean_lib]]
name = "CpcMini"

[[lean_exe]]
name = "logos"
root = "Main"

[[lean_exe]]
name = "logos-native"
root = "MainNative"
supportInterpreter = true

[[lean_exe]]
name = "logos-mini"
root = "MainMini"

[[lean_exe]]
name = "logos-mini-native"
root = "MainMiniNative"
supportInterpreter = true
