name = "Cpc"
version = "0.1.0"
defaultTargets = ["Logos", "Cpc", "CpcMini"]

[[lean_lib]]
name = "Logos"

[[lean_lib]]
name = "Cpc"
moreLeanArgs = ["-DmaxHeartbeats=10000000", "-DwarningAsError=true"]

[[lean_lib]]
name = "CpcMini"
moreLeanArgs = ["-DwarningAsError=true"]

[[lean_exe]]
name = "logos"
root = "Main"

[[lean_exe]]
name = "logos-native"
root = "MainNative"
supportInterpreter = true
